variables:
  BRANCH: ""
  REPO: ""

default:
  image: ubuntu
  tags:
    - docker-runner-frontend

stages:
  - checkBranch
  - buildImage
  - pushImage

devUnitTest:
  stage: checkBranch
  script:
    - echo "Running unit tests for development branch"
    # do unit tests if all good do the rest else return 1
    - export BRANCH="dev"
    - export REPO=$DEV_FRONTEND_REPO
  only:
    - ci/cd

buildImage:
  stage: buildImage
  image: docker:24.0.7
  services:
    - docker:dind
  script:
    - echo $BRANCH
    - echo $REPO
    - docker build -t $BRANCH-frontend-image .
    - docker save -o $BRANCH-frontend-image.tar $BRANCH_ENV-frontend-image
  dependencies:
    - devUnitTest
  artifacts:
    paths:
      - $BRANCH-frontend-image.tar

pushImage:
  stage: pushImage
  image: google/cloud-sdk
  script:
    - touch gcloud-service-key.json
    - echo "$GCLOUD_SERVICE_KEY" > gcloud-service-key.json
    - cat gcloud-service-key.json
    - gcloud auth activate-service-account --key-file=gcloud-service-key.json
    - gcloud auth configure-docker europe-west1-docker.pkg.dev
    # Load the Docker image from the tarball
    - docker load -i $$BRANCH-frontend-image.tar
    # Push the Docker image to the specified repository
    - docker tag $BRANCH-frontend-image:latest $REPO
    - docker push $REPO