default:
  image: ubuntu
  tags:
    - docker-runner-frontend

stages:
  # - buildSite
  - buildImage
  - pushImage 

# build_site:
#   stage: buildSite
#   image: $NODE_IMAGE
#   script:
#     - ls -al
#     - npm install
#     - npm run build 
#     - ls -al
#   artifacts: 
#     paths:
#       - ".next"


buildImage:
  stage: buildImage
  image: docker:latest
  script:
    - docker --version
    - echo "FROM nginx:latest" > Dockerfile
    # - echo "COPY .next /usr/share/nginx/html/.next" >> Dockerfile  
    - echo "COPY custom.conf /etc/nginx/conf.d/default.conf" >> Dockerfile
    - cat Dockerfile
    - docker build -t dev-frontend .


push_image:
  stage: pushImage
  image: google/cloud-sdk
  script:
    - touch gcloud-service-key.json
    - echo "$GCLOUD_SERVICE_KEY" > gcloud-service-key.json
    - cat gcloud-service-key.json
    - gcloud auth activate-service-account --key-file=gcloud-service-key.json
    - gcloud config set project $PROJECT_ID
    - gcloud auth configure-docker

    


    
    

    





