default:
  image: ubuntu
  tags:
    - atpfrontendRunner

stages:
  - build

variables:
  NODE_IMAGE: "node:14"  # Set the Node.js image version you want to use

build:
  stage: build
  image: $NODE_IMAGE
  script:
    - ls -al
    - sudo npm install
    - sudo npm run build
    - ls -al
