default:
  image: ubuntu
  tags:
    - atpFrontendRunnertest

stages:
  # - buildSite
  - buildImage
  - pushImage 

# build_site:
#   stage: buildSite
#   image: $NODE_IMAGE
#   script:
#     - ls -al
#     - npm install
#     - npm run build 
#     - ls -al
#   artifacts: 
#     paths:
#       - ".next"

stages:
  - buildImage

buildImage:
  stage: buildImage
  image: $DOCKER_IMAGE
  services:
    - name: docker:dind
      entrypoint: ["bash", "-c"]
      command: ["dockerd-entrypoint.sh --host tcp://docker:2375"]
  script:
    - docker --version
    - echo "FROM nginx:latest" > Dockerfile
    # - echo "COPY .next /usr/share/nginx/html/.next" >> Dockerfile  
    - echo "COPY custom.conf /etc/nginx/conf.d/default.conf" >> Dockerfile
    - echo "RUN rm /etc/nginx/conf.d/default.conf" >> Dockerfile
    - cat Dockerfile
    - docker build -t $BACKEND_REPO .
    - ls -all


push_image:
  stage: pushImage
  image: google/cloud-sdk
  script:
    - echo $GCLOUD_SERVICE_KEY | base64 -d > gcloud-service-key.json
    - gcloud auth activate-service-account --key-file=gcloud-service-key.json
    - gcloud config set project $PROJECT_ID
    - gcloud auth configure-docker
    - docker push $BACKEND_REPO

    





