---
# tasks file for createEnvFile
  - name: Ensure directory exists
    file:
      path: ./infra
      state: directory

  - name: Create .env file with touch if it doesn't exist
    command: touch ./infra/.env
    args:
      creates: ./infra/.env  # Only execute if the file doesn't exist yet

  - name: Insert variables into .env file
    blockinfile:
      path: ./infra/.env
      block: |
        DEV_FRONTEND_REPO={{ dev_frontend_repo }}
        DEV_BACKEND_REPO={{ dev_backend_repo }}
        MYSQL_ROOT_PASSWORD={{ mysql_root_password }}
        MYSQL_DATABASE={{ mysql_database }}
