// import { Inter } from "next/font/google";
import Header from "@/organisms/header";
import "./globals.css";
import Footer from "@/organisms/footer";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://unpkg.com/normalize.css" />
      </head>
      {/* <body className={inter.className}>{children}</body> */}
      <body>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
