---
all:
  children:
    host:
      hosts:
        controlnode1:
          ansible_host: localhost
    dev:
      hosts:
        node1:
          ansible_host: 10.129.23.204
   #  staging:
   #    hosts:
   #      node1:
   #        ansible_host: 10.129.23.248
   #  prod:
   #    hosts:
   #      node1:
   #        ansible_host: 10.129.23.248

  


   

      

  