---
- name: Authenticate to Google Cloud
  hosts: 
    - "{{target_host}}"
  become_user: "{{ ansible_user }}" 
  tasks:
    - name: Include gcloudAuthArtifactRegistry for non-dev hosts
      include_role:
        name: gcloudAuthArtifactRegistry
      when: "'dev' not in inventory_hostname"

- name : update the containers on the servers 
  hosts: 
    - "{{target_host}}"
  roles:
    - updateDockerContainers

- name: Run commands inside Docker container
  hosts:
    - "{{target_host}}"
  command: >
    docker exec -it backend_web bash -c '
      cp .env.example .env &&
      composer install &&
      php artisan key:generate &&
      touch storage/logs/laravel.log &&
      chmod 777 -R storage bootstrap/cache &&
      php artisan storage:link &&
      exit
    '

    
